{% set name = "conda-forge-feedstock-check-solvable" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-check-solvable/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5cdfcb0b41c50f7fd2c3d92e577267e16d58ef691943de852bc105e96346b713

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm >=7
    - setuptools >=45
  run:
    - python >=3.7
    - python-rapidjson
    - requests
    - ruamel.yaml
    - cachetools
    - conda
    - conda-package-handling
    - conda-smithy
    - conda-build
    - mamba >=1.5.1
    - ruamel.yaml.jinja2
    - conda-forge-metadata >=0.2.0
    - wurlitzer
    - psutil
    - libmambapy
    - zstandard
    - boltons >=23.0.0

test:
  imports:
    - conda_forge_feedstock_check_solvable

about:
  home: https://github.com/regro/conda-forge-feedstock-check-solvable
  summary: A mamba-based package to check if a conda-forge feedstock is solvable.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - xhochy
