{% set name = "conda-forge-feedstock-check-solvable" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-check-solvable/archive/refs/tags/{{ version }}.tar.gz
  sha256: 472ce7fa0db878ea871816299ff03d958f37d359d370830525319e1f5a24bc2a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-rapidjson
    - requests
    - ruamel.yaml
    - cachetools
    - conda
    - conda-package-handling
    - conda-smithy
    - conda-build
    - mamba >=0.23
    - ruamel.yaml.jinja2
    - conda-forge-metadata >=0.2.0

test:
  imports:
    - conda_forge_feedstock_check_solvable

about:
  home: https://github.com/regro/conda-forge-feedstock-check-solvable
  summary: A mamba-based package to check if a conda-forge feedstock is solvable.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
